### ISSUE TITLE
target timeframes in past change on reload/restart

### ISSUE THREAD

**Issue by BottlecapDave** [BottlecapDave/HomeAssistant-TargetTimeframes#58]
I am not using free electricity weightings or carbon intensity to influence the target times. The data source hasn't changed to my knowledge. I just took some screenshots in case that helps.

Target timeframe sensor, before reloading data source. Target time of 0100:
<img width="578" height="1249" alt="Screenshot 2025-09-08 at 09 59 50" src="https://github.com/user-attachments/assets/9425cce2-4890-4cab-86c6-ea9680d13879" />

Target timeframe sensor, after reloading data source. New target time of 1330. Nothing else changed in the configuration.
<img width="593" height="1280" alt="Screenshot 2025-09-08 at 10 00 47" src="https://github.com/user-attachments/assets/acc20e17-8b1d-4283-bf50-a329a86e5198" />

Octopus Energy integration. Target times last evaluated again just now at 1027, target time for period still 0100
<img width="574" height="1257" alt="Screenshot 2025-09-08 at 10 28 38" src="https://github.com/user-attachments/assets/3b58a164-e103-4190-90ca-6c0052d3fe84" />

_Originally posted by @jon273 in https://github.com/BottlecapDave/HomeAssistant-TargetTimeframes/discussions/45#discussioncomment-14338373_

**Comment by BottlecapDave** [comment]
This should be fixed as part of [v1.4.1](https://github.com/BottlecapDave/HomeAssistant-TargetTimeframes/releases/tag/v1.4.1)

**Comment by jon273** [comment]
Unfortunately I am still seeing the same behaviour. I just changed the target hours from 4 to 2 for my UFH and it just came on now even though it was already on at 23:00 last night for the specified hours at a cheaper rate. Reloading the integration makes it look from the time of reloading until 16:00 and picking the cheapest slots in that timeframe. The Octopus Energy target (v17.1.1.) will still select target hours in the past if set from 16:00-16:00

**Comment by BottlecapDave** [comment]
If you change the target hours, this null and voids taking into account when the sensor last came on during it's calculations as it's no longer the "same" sensor. This is how the OE sensor works.

**Comment by jon273** [comment]
In the OE integration it does not work like that. With OE I can change target hours and it will reassess over the whole 24h period and select target hours in the past if they are the cheapest. With Target Timeframes integration it will reassess from now until the specified assessment period end time and ignore any cheap slots in the past. This means when changing target hours in TT I have to disable my automations until 16:00 otherwise stuff ends up switching back on again. Hardly the end of the world, but it's different to how it works in OE, which I was not expecting.

OE sensor, target hours 1.0 (all target times are in the past, screenshots taken 09:16)
<img width="585" height="1251" alt="Image" src="https://github.com/user-attachments/assets/c25d23dd-15c2-421d-9724-491a5f6cd2c0" />

OE sensor, target hours changed to 1.5 (all target times are in the past. Sensor will be active for 1.5 hours over next assessment period. Not a problem because by hot water was already on for 1 hour last night)
<img width="584" height="1267" alt="Image" src="https://github.com/user-attachments/assets/fb08d9ec-a249-4ae2-80c2-c1becec06eb1" />

TT sensor, target hours 1.0 (all target times are in the past)
<img width="578" height="1270" alt="Image" src="https://github.com/user-attachments/assets/3598f91c-8f40-47c1-9c82-74917a82df41" />

TT sensor, target hours 1.5 (new target times have been calculated, ignoting the cheaper slots which are already in the past. End result: sensor will be active for 2.5h total over today's 24h period)
<img width="568" height="1238" alt="Image" src="https://github.com/user-attachments/assets/88b64465-a58c-4cd0-89c9-e8e644d2a314" />


Your integration is great by the way, and for me Agile would be pointless without it. I am using it to control all of my electric underfloor storage heating. Unfortunately since switching from OE to TT my apartment has ended up like an oven a couple of times because of this.
